### ISSUE TITLE
Add an English language to the RPC

### ISSUE THREAD

**Issue by urfavgothh** [yuzune27/IfnikkiRPC#2]
Hello I was wondering if you could maybe add a "English" version for another version of the RPC. I love it alot.

**Comment by yuzune27** [comment]
Hello.
v1.4.0 has been released with support for English notation. (→ [Releases](https://github.com/yuzune27/IfnikkiRPC/releases/tag/v1.4.0))
Please check to see if it works properly.

![en](https://github.com/user-attachments/assets/b4ff7d8a-4a2e-45a9-8917-45e4f1d6e653)

**Comment by urfavgothh** [comment]
Thank you so much, will test it

**Comment by urfavgothh** [comment]
It works!

**Comment by yuzune27** [comment]
I'm glad to hear that :)
Have a good time.
